"use client";

import { Search, Shuffle, Sparkles } from "lucide-react";
import { useMemo, useState } from "react";
import { verbs, examplesForVerb } from "@/data/verbs";
import { AudioButton } from "@/components/exercises/audio-button";
import { PageHeader } from "@/components/ui/page-header";

export default function VerbsPage() {
  const [query, setQuery] = useState("");
  const [selectedBase, setSelectedBase] = useState("go");
  const filtered = useMemo(() => verbs.filter((verb) => `${verb.base} ${verb.meaning}`.toLowerCase().includes(query.toLowerCase())), [query]);
  const verb = verbs.find((item) => item.base === selectedBase) ?? verbs[0];
  const forms = [{ label: "Base", value: verb.base }, { label: "He / she / it", value: verb.third }, { label: "Past", value: verb.past }, { label: "Participle", value: verb.participle }, { label: "Gerund", value: verb.gerund }];
  function randomVerb() { setSelectedBase(verbs[Math.floor(Math.random() * verbs.length)].base); }

  return <div className="animate-rise"><PageHeader eyebrow="Laboratorio de Verbos" title="Aprende familias, no traducciones" description="Observa cómo se transforma cada verbo y úsalo en escenas reales." action={<button onClick={randomVerb} className="secondary-button"><Shuffle size={16} /> Verbo al azar</button>} /><div className="mt-7 grid gap-5 xl:grid-cols-[330px_1fr]">
    <aside className="surface max-h-[720px] overflow-hidden"><div className="border-b border-forest/10 p-4"><label className="flex h-12 items-center gap-2 rounded-2xl bg-cream px-3 text-forest/40"><Search size={17} /><input value={query} onChange={(event) => setQuery(event.target.value)} placeholder="Buscar verbo o significado" className="min-w-0 flex-1 bg-transparent text-sm font-semibold text-forest outline-none placeholder:text-forest/30" /></label><p className="mt-3 px-1 text-[10px] font-bold uppercase tracking-wider text-forest/35">{filtered.length} verbos · Toca para explorar</p></div><div className="max-h-[620px] space-y-1 overflow-y-auto p-2">{filtered.map((item) => <button key={item.base} onClick={() => setSelectedBase(item.base)} className={`flex w-full items-center justify-between rounded-2xl px-4 py-3 text-left transition ${verb.base === item.base ? "bg-forest text-white" : "hover:bg-cream"}`}><span><span className="block text-sm font-black uppercase">{item.base}</span><span className={`text-[11px] ${verb.base === item.base ? "text-white/50" : "text-forest/40"}`}>{item.meaning}</span></span>{item.irregular && <span className={`rounded-full px-2 py-1 text-[9px] font-bold ${verb.base === item.base ? "bg-white/10 text-lime" : "bg-coral/10 text-coral"}`}>irregular</span>}</button>)}</div></aside>
    <section className="surface overflow-hidden"><div className="soft-grid bg-mint/45 p-6 sm:p-8"><div className="flex items-start justify-between gap-4"><div><div className="flex items-center gap-2"><span className="eyebrow">Verbo #{verbs.findIndex((item) => item.base === verb.base) + 1}</span>{verb.irregular && <span className="rounded-full bg-white/65 px-2 py-1 text-[9px] font-bold text-coral">Irregular</span>}</div><h2 className="mt-2 text-5xl font-black uppercase tracking-[-0.05em] text-ink sm:text-6xl">{verb.base}</h2><p className="mt-2 text-sm font-bold text-forest/55">{verb.meaning}</p></div><AudioButton text={verb.base} compact /></div><div className="mt-8 grid grid-cols-2 gap-2 sm:grid-cols-5">{forms.map((form) => <div key={form.label} className="rounded-2xl bg-white/70 p-3"><span className="block text-[9px] font-black uppercase tracking-wider text-forest/35">{form.label}</span><span className="mt-1 block text-base font-black text-forest">{form.value}</span></div>)}</div></div>
    <div className="p-6 sm:p-8"><div className="flex items-center gap-2"><Sparkles size={17} className="text-moss" /><h3 className="text-sm font-black text-ink">La familia en contexto</h3></div><div className="mt-4 space-y-2">{examplesForVerb(verb).map((example) => <div key={`${example.label}-${example.sentence}`} className="group flex items-center gap-3 rounded-2xl border border-forest/8 p-3.5 transition hover:bg-cream"><span className="w-20 shrink-0 text-[10px] font-black uppercase tracking-wider text-moss">{example.label}</span><div className="min-w-0 flex-1"><p className="text-sm font-bold text-forest">{example.sentence}</p><p className="mt-0.5 text-[10px] text-forest/35">{example.note}</p></div><AudioButton text={example.sentence} compact /></div>)}</div><div className="mt-6 rounded-2xl bg-[#fff6e6] p-4 text-sm leading-6 text-forest/65"><strong className="text-forest">Conecta las formas:</strong> no memorices “{verb.base} = {verb.meaning}”. Recuerda una escena para {verb.past} y otra para {verb.participle}.</div></div></section>
  </div></div>;
}
